// Code generated by mockery v2.53.3. DO NOT EDIT.

package loading

import (
	mock "github.com/stretchr/testify/mock"
	blockchain "github.com/thewizardplusplus/go-blockchain"
)

// MockLoader is an autogenerated mock type for the Loader type
type MockLoader struct {
	mock.Mock
}

// LoadBlocks provides a mock function with given fields: cursor, count
func (_m *MockLoader) LoadBlocks(cursor interface{}, count int) (blockchain.BlockGroup, interface{}, error) {
	ret := _m.Called(cursor, count)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlocks")
	}

	var r0 blockchain.BlockGroup
	var r1 interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, int) (blockchain.BlockGroup, interface{}, error)); ok {
		return rf(cursor, count)
	}
	if rf, ok := ret.Get(0).(func(interface{}, int) blockchain.BlockGroup); ok {
		r0 = rf(cursor, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blockchain.BlockGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, int) interface{}); ok {
		r1 = rf(cursor, count)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, int) error); ok {
		r2 = rf(cursor, count)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockLoader creates a new instance of MockLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoader {
	mock := &MockLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
