// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package blockchain

import mock "github.com/stretchr/testify/mock"

// MockDataComparer is an autogenerated mock type for the DataComparer type
type MockDataComparer struct {
	mock.Mock
}

// Equal provides a mock function with given fields: data
func (_m *MockDataComparer) Equal(data Data) bool {
	ret := _m.Called(data)

	var r0 bool
	if rf, ok := ret.Get(0).(func(Data) bool); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
