// Code generated by mockery v2.53.3. DO NOT EDIT.

package blockchain

import mock "github.com/stretchr/testify/mock"

// MockTextMarshaler is an autogenerated mock type for the TextMarshaler type
type MockTextMarshaler struct {
	mock.Mock
}

// MarshalText provides a mock function with no fields
func (_m *MockTextMarshaler) MarshalText() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarshalText")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTextMarshaler creates a new instance of MockTextMarshaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTextMarshaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTextMarshaler {
	mock := &MockTextMarshaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
