// Code generated by mockery v2.53.3. DO NOT EDIT.

package blockchain

import mock "github.com/stretchr/testify/mock"

// MockDataComparer is an autogenerated mock type for the DataComparer type
type MockDataComparer struct {
	mock.Mock
}

// Equal provides a mock function with given fields: data
func (_m *MockDataComparer) Equal(data Data) bool {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Equal")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(Data) bool); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockDataComparer creates a new instance of MockDataComparer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataComparer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataComparer {
	mock := &MockDataComparer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
