// Code generated by mockery v2.53.3. DO NOT EDIT.

package storing

import (
	mock "github.com/stretchr/testify/mock"
	blockchain "github.com/thewizardplusplus/go-blockchain"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// DeleteBlock provides a mock function with given fields: block
func (_m *MockStorage) DeleteBlock(block blockchain.Block) error {
	ret := _m.Called(block)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(blockchain.Block) error); ok {
		r0 = rf(block)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadBlocks provides a mock function with given fields: cursor, count
func (_m *MockStorage) LoadBlocks(cursor interface{}, count int) (blockchain.BlockGroup, interface{}, error) {
	ret := _m.Called(cursor, count)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlocks")
	}

	var r0 blockchain.BlockGroup
	var r1 interface{}
	var r2 error
	if rf, ok := ret.Get(0).(func(interface{}, int) (blockchain.BlockGroup, interface{}, error)); ok {
		return rf(cursor, count)
	}
	if rf, ok := ret.Get(0).(func(interface{}, int) blockchain.BlockGroup); ok {
		r0 = rf(cursor, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blockchain.BlockGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, int) interface{}); ok {
		r1 = rf(cursor, count)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	if rf, ok := ret.Get(2).(func(interface{}, int) error); ok {
		r2 = rf(cursor, count)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LoadLastBlock provides a mock function with no fields
func (_m *MockStorage) LoadLastBlock() (blockchain.Block, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadLastBlock")
	}

	var r0 blockchain.Block
	var r1 error
	if rf, ok := ret.Get(0).(func() (blockchain.Block, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() blockchain.Block); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(blockchain.Block)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreBlock provides a mock function with given fields: block
func (_m *MockStorage) StoreBlock(block blockchain.Block) error {
	ret := _m.Called(block)

	if len(ret) == 0 {
		panic("no return value specified for StoreBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(blockchain.Block) error); ok {
		r0 = rf(block)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
